project:
  type: book
  output-dir: ../docs

book:
  title: "mybook"
  author: "Norah Jones"
  date: "17-09-2024"
  chapters:
    - index.qmd
    - 01-exploracion.qmd
    # - summary.qmd
    # - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



