% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\PassOptionsToPackage{dvipsnames,svgnames,x11names}{xcolor}
%
\documentclass[
  12pt,
]{book}
\usepackage{amsmath,amssymb}
\usepackage{setspace}
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\usepackage[left=4cm, right=3cm, top=2.5cm, bottom=2.5cm]{geometry}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}
\usepackage[utf8]{inputenc}
\usepackage[spanish,es-tabla]{babel}
\usepackage[fixlanguage]{babelbib}
\usepackage{geometry}
\geometry{letterpaper,left=2cm,top=2cm, right=2cm}
\usepackage{times}           
\usepackage{caption}
\captionsetup[figure, table]{labelfont={bf},labelformat={default},labelsep=period}
\usepackage{graphicx}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
%\usepackage{float}
\usepackage{colortbl}
\usepackage{xcolor}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{pdfpages}
\usepackage{hyphsubst}
\usepackage{floatrow}
\floatsetup[figure]{capposition=top}
\floatsetup[table]{capposition=top}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifLuaTeX
  \usepackage{selnolig}  % disable illegal ligatures
\fi
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Efectos políticos de las huelgas},
  pdfauthor={Equipo Fondecyt},
  colorlinks=true,
  linkcolor={blue},
  filecolor={Maroon},
  citecolor={Blue},
  urlcolor={Blue},
  pdfcreator={LaTeX via pandoc}}

\title{Efectos políticos de las huelgas}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{con ELSOC 2016-2022}
\author{Equipo Fondecyt}
\date{}

\begin{document}
\maketitle

{
\hypersetup{linkcolor=}
\setcounter{tocdepth}{1}
\tableofcontents
}
\listoffigures
\listoftables
\setstretch{1.5}
\hypertarget{presentaciuxf3n}{%
\chapter*{Presentación}\label{presentaciuxf3n}}
\addcontentsline{toc}{chapter}{Presentación}

Preparación y exploración de datos ELSOC 2016-2022 para analizar variables que puedan relacionarse a los efectos políticos de las huelgas.

Se debe considerar que los ítems del cuestionario ELSOC no se presentan en todas las olas.

Las olas corresponden a los siguientes años:

\begin{itemize}
\tightlist
\item
  Ola 1: 2016
\item
  Ola 2: 2017
\item
  Ola 3: 2018
\item
  Ola 4: 2019
\item
  Ola 5: 2021
\item
  Ola 6: 2022
\end{itemize}

En abril de 2024 se contará con la séptima ola correspondiente al año 2023.

\hypertarget{preparaciuxf3n-y-exploraciuxf3n-datos}{%
\chapter{Preparación y exploración datos}\label{preparaciuxf3n-y-exploraciuxf3n-datos}}

\hypertarget{exploraciuxf3n-variables-de-interuxe9s}{%
\section{Exploración variables de interés}\label{exploraciuxf3n-variables-de-interuxe9s}}

\hypertarget{caracterizaciuxf3n-empleo}{%
\subsection{Caracterización empleo}\label{caracterizaciuxf3n-empleo}}

Primero, una revisión exploratoria de las variables de interés, considerando toda la base de datos, sin ponderar.

\begin{itemize}
\tightlist
\item
  m02. ¿Cuál de estas situaciones describe mejor su actividad principal durante el último mes?
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-1}Frecuencias de cada categoría de Actividad por ola}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
actividad & 2016 & 2017 & 2018 & 2019 & 2021 & 2022\\
\hline
Trabaja de manera remunerada con jornada completa & 1391 & 1116 & 1688 & 1501 & 1095 & 1137\\
\hline
Trabaja de manera remunerada a tiempo parcial & 351 & 362 & 537 & 560 & 484 & 456\\
\hline
Estudia y trabaja & 60 & 71 & 90 & 68 & 62 & 49\\
\hline
Solo estudia & 101 & 75 & 116 & 77 & 51 & 36\\
\hline
Jubilado o pensionado & 371 & 345 & 479 & 499 & 433 & 545\\
\hline
Desempleado, buscando trabajo & 166 & 73 & 198 & 154 & 172 & 119\\
\hline
Realiza tareas no remuneradas & 367 & 332 & 443 & 449 & 366 & 294\\
\hline
Esta enfermo o tiene una discapacidad & 24 & 17 & 29 & 32 & 44 & 28\\
\hline
No estudia, no trabaja y no busca trabajo & 90 & 77 & 152 & 67 & 33 & 59\\
\hline
 & 6 & 5 & 16 & 10 &  & 7\\
\hline
\end{tabular}
\end{table}

\begin{itemize}
\item
  m03. ¿Cuál es su ocupación u oficio actual? Describa sus principales tareas y funciones en el puesto de trabajo actual
\item
  ciuo88\_m03: CIUO (1988) del entrevistado
\item
  ciuo08\_m03: CIUO (2008) del entrevistado
\end{itemize}

\begin{verbatim}
## 
## 0110 1221 1222 1223 1225 1226 1227 1229 1231 1311 1312 1314 1315 1316 1317 1319 
##    3    2    2    2    2    2    2   11    2   11    2    2    2    2    7    9 
## 2113 2131 2132 2139 2141 2144 2149 2211 2212 2221 2229 2230 2310 2320 2359 2411 
##    2    7    3    3    3    2    3    2    3    2    2    6    2    2    5    2 
## 2412 2419 2451 2455 3114 3121 3122 3131 3132 3151 3152 3211 3212 3221 3222 3224 
##    3    7    4    2    2    3    2    2    2    2    7    2    2    3    2    2 
## 3226 3229 3241 3340 3411 3415 3417 3431 3434 3439 3450 3471 3472 3473 3475 4111 
##    4    5    2    8    2    3    2    4    2    4    2    5    2    2    3    2 
## 4112 4114 4115 4121 4122 4131 4132 4133 4141 4142 4143 4144 4190 4211 4222 4223 
##    2    2    4    3    2    2    2    2    3    2    3    2    5    3    6    2 
## 5121 5122 5123 5131 5132 5139 5141 5169 5220 5230 6113 6124 6129 6152 6210 7111 
##    2    3    2    2    3    2    2    2    6    2    2    3    2    2    4    2 
## 7122 7129 7143 7231 7233 7242 7243 7245 7311 7322 7331 7341 7432 8111 8121 8122 
##    2    3    2    2    2    2    2    2    2    2    2    2    2    2    2    2 
## 8123 8124 8142 8143 8152 8153 8154 8155 8159 8171 8172 8211 8221 8222 8223 8224 
##    2    2    2    2    2    2    2    2    2    2    2    2    2    2    2    2 
## 8229 8231 8232 8240 8251 8252 8253 8261 8262 8263 8264 8265 8266 8269 8271 8272 
##    2    2    2    2    2    2    2    2    2    2    3    2    2    2    2    2 
## 8273 8274 8275 8276 8277 8278 8279 8281 8282 8283 8284 8285 8286 8290 9113 9132 
##    2    2    2    2    2    2    2    2    2    2    2    2    2    4    2    2 
## 9142 9152 9161 9162 9211 9321 9322 9333 
##    3    3    2    3    4    2    2    2
\end{verbatim}

\begin{verbatim}
## 
## 1114 1211 1212 1213 1219 1221 1222 1223 1321 1322 1323 1324 1330 1341 1342 1343 
##    3    2    2    2    6    2    2    2    2    2    2    3    4    2    3    3 
## 1344 1345 1346 1349 1411 1412 1420 1439 2120 2131 2132 2212 2230 2250 2262 2263 
##    2    2    2    2    2    2    2    2    2    2    2    2    2    2    2    4 
## 2267 2269 2320 2341 2342 2351 2352 2353 2355 2356 2359 2412 2431 2432 2513 2519 
##    2    3    2    2    2    2    2    2    2    2    2    3    2    2    3    3 
## 2642 2652 2653 2654 3112 3113 3114 3115 3117 3121 3122 3123 3133 3135 3139 3153 
##    2    2    2    2    2    2    2    2    2    2   37    2    4    4    5    2 
## 3221 3222 3257 3259 3313 3339 3341 3342 3343 3344 3359 3411 3413 3423 3433 3435 
##    2    2    2    2    2    3   17    2    2    2    3    2    2    2    2    3 
## 3514 3521 3522 4131 4132 4211 4212 4221 5161 5164 5246 5329 5414 6111 6112 6113 
##    2    2    2    2    2    2    2    2    2    2    2    2    2    2    2    2 
## 6114 6121 6122 6123 6130 6210 6221 6222 6223 7111 7113 7223 7316 7317 7318 7321 
##    2    3    3    2    2    3    2    2    2    2    2    2    2    2    3    3 
## 7322 7323 7421 7422 7523 7531 7541 8111 8121 8131 8132 8152 8160 8171 8181 8212 
##    3    2    2    4    2    2    2    2    4    9    2    2    9    2    2    2 
## 8219 9214 9329 9612 9621 
##    4    2    2    2    2
\end{verbatim}

\begin{table}

\caption{\label{tab:unnamed-chunk-2}Frecuencias de cada categoría de Ocupación por ola}
\centering
\begin{tabular}[t]{r|r|r|r|r|r|r}
\hline
isco08\_1d & 2016 & 2017 & 2018 & 2019 & 2021 & 2022\\
\hline
1 & 89 &  & 58 &  & 41 & \\
\hline
2 & 257 &  & 308 &  & 248 & \\
\hline
3 & 362 &  & 175 &  & 147 & \\
\hline
4 & 26 &  & 187 &  & 127 & \\
\hline
5 & 348 &  & 573 &  & 378 & \\
\hline
6 & 41 &  & 25 &  & 30 & \\
\hline
7 & 319 &  & 343 &  & 294 & \\
\hline
8 & 120 &  & 202 &  & 125 & \\
\hline
9 & 220 &  & 444 &  & 251 & \\
\hline
 & 1145 & 2473 & 1433 & 3417 & 1099 & 2730\\
\hline
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:unnamed-chunk-2}Frecuencias de cada categoría de Ocupación por ola}
\centering
\begin{tabular}[t]{r|r|r|r|r|r|r}
\hline
isco08\_2d & 2016 & 2017 & 2018 & 2019 & 2021 & 2022\\
\hline
12 & 14 &  & 8 &  & 2 & \\
\hline
13 & 15 &  & 22 &  & 3 & \\
\hline
14 & 60 &  & 22 &  & 28 & \\
\hline
21 & 47 &  & 52 &  & 50 & \\
\hline
22 & 34 &  & 37 &  & 26 & \\
\hline
23 & 82 &  & 125 &  & 86 & \\
\hline
24 & 45 &  & 41 &  & 35 & \\
\hline
25 & 6 &  & 7 &  & 15 & \\
\hline
26 & 43 &  & 46 &  & 36 & \\
\hline
31 & 54 &  & 32 &  & 37 & \\
\hline
32 & 29 &  & 42 &  & 42 & \\
\hline
33 & 209 &  & 68 &  & 54 & \\
\hline
34 & 63 &  & 24 &  & 9 & \\
\hline
35 & 7 &  & 8 &  & 5 & \\
\hline
41 & 2 &  & 74 &  & 11 & \\
\hline
42 & 24 &  & 43 &  & 24 & \\
\hline
51 & 54 &  & 134 &  & 84 & \\
\hline
52 & 180 &  & 299 &  & 182 & \\
\hline
53 & 49 &  & 76 &  & 65 & \\
\hline
54 & 65 &  & 64 &  & 47 & \\
\hline
61 & 34 &  & 22 &  & 19 & \\
\hline
62 & 7 &  & 1 &  & 10 & \\
\hline
71 & 123 &  & 109 &  & 96 & \\
\hline
72 & 62 &  & 82 &  & 51 & \\
\hline
73 & 7 &  & 20 &  & 11 & \\
\hline
74 & 29 &  & 34 &  & 31 & \\
\hline
75 & 98 &  & 98 &  & 105 & \\
\hline
81 & 6 &  & 52 &  & 37 & \\
\hline
83 & 114 &  & 149 &  & 87 & \\
\hline
91 & 154 &  & 206 &  & 152 & \\
\hline
92 & 15 &  & 43 &  & 36 & \\
\hline
93 & 27 &  & 83 &  & 36 & \\
\hline
95 & 14 &  & 18 &  & 15 & \\
\hline
96 & 10 &  & 16 &  & 7 & \\
\hline
 & 1145 & 2473 & 1433 & 3417 & 1099 & 2730\\
\hline
11 &  &  & 6 &  & 8 & \\
\hline
36 &  &  & 1 &  &  & \\
\hline
43 &  &  & 57 &  & 55 & \\
\hline
44 &  &  & 13 &  & 36 & \\
\hline
63 &  &  & 2 &  & 1 & \\
\hline
82 &  &  & 1 &  & 1 & \\
\hline
94 &  &  & 24 &  & 5 & \\
\hline
99 &  &  & 54 &  &  & \\
\hline
47 &  &  &  &  & 1 & \\
\hline
\end{tabular}
\end{table}

\begin{verbatim}
## package 'ISCO08ConveRsions' successfully unpacked and MD5 sums checked
## 
## The downloaded binary packages are in
##  C:\Users\danie\AppData\Local\Temp\RtmpAfAkmF\downloaded_packages
\end{verbatim}

\begin{verbatim}
## [1] 377
\end{verbatim}

\begin{verbatim}
## [1] 147
\end{verbatim}

\begin{table}

\caption{\label{tab:unnamed-chunk-5}Frecuencias de cada categoría de Ocupación por ola}
\centering
\begin{tabular}[t]{r|r|r|r|r|r|r}
\hline
isco08\_2d & 2016 & 2017 & 2018 & 2019 & 2021 & 2022\\
\hline
11 & 4 &  & 6 &  & 8 & \\
\hline
12 & 78 &  & 8 &  & 2 & \\
\hline
13 & 20 &  & 22 &  & 3 & \\
\hline
21 & 167 &  & 52 &  & 50 & \\
\hline
22 & 86 &  & 37 &  & 26 & \\
\hline
23 & 82 &  & 125 &  & 86 & \\
\hline
31 & 172 &  & 32 &  & 37 & \\
\hline
32 & 344 &  & 42 &  & 42 & \\
\hline
33 & 40 &  & 68 &  & 54 & \\
\hline
51 & 277 &  & 134 &  & 84 & \\
\hline
52 & 177 &  & 299 &  & 182 & \\
\hline
71 & 88 &  & 109 &  & 96 & \\
\hline
73 & 100 &  & 20 &  & 11 & \\
\hline
83 & 114 &  & 149 &  & 87 & \\
\hline
92 & 15 &  & 43 &  & 36 & \\
\hline
93 & 27 &  & 83 &  & 36 & \\
\hline
 & 1136 & 2473 & 1433 & 3417 & 1099 & 2730\\
\hline
14 &  &  & 22 &  & 28 & \\
\hline
24 &  &  & 41 &  & 35 & \\
\hline
25 &  &  & 7 &  & 15 & \\
\hline
26 &  &  & 46 &  & 36 & \\
\hline
34 &  &  & 24 &  & 9 & \\
\hline
35 &  &  & 8 &  & 5 & \\
\hline
36 &  &  & 1 &  &  & \\
\hline
41 &  &  & 74 &  & 11 & \\
\hline
42 &  &  & 43 &  & 24 & \\
\hline
43 &  &  & 57 &  & 55 & \\
\hline
44 &  &  & 13 &  & 36 & \\
\hline
53 &  &  & 76 &  & 65 & \\
\hline
54 &  &  & 64 &  & 47 & \\
\hline
61 &  &  & 22 &  & 19 & \\
\hline
62 &  &  & 1 &  & 10 & \\
\hline
63 &  &  & 2 &  & 1 & \\
\hline
72 &  &  & 82 &  & 51 & \\
\hline
74 &  &  & 34 &  & 31 & \\
\hline
75 &  &  & 98 &  & 105 & \\
\hline
81 &  &  & 52 &  & 37 & \\
\hline
82 &  &  & 1 &  & 1 & \\
\hline
91 &  &  & 206 &  & 152 & \\
\hline
94 &  &  & 24 &  & 5 & \\
\hline
95 &  &  & 18 &  & 15 & \\
\hline
96 &  &  & 16 &  & 7 & \\
\hline
99 &  &  & 54 &  &  & \\
\hline
47 &  &  &  &  & 1 & \\
\hline
\end{tabular}
\end{table}

\begin{itemize}
\item
  m04. ¿A qué rubro o giro de actividad se dedica principalmente la empresa, institución o negocio para la cual usted trabaja?
\item
  ciiu3\_m04: CIIU (III version) del entrevistado
\item
  ciiu4\_m04: CIIU (IV version) del entrevistado
\item
  m07. En su actual ocupación usted trabaja como:
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-7}Frecuencias de cada categoría de Relación de Empleo por ola}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
rel\_empleo & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Empleado u obrero en empresa privada & 1091 &  & 1338 &  & 883 & \\
\hline
Empleado u obrero del sector público & 186 &  & 290 &  & 228 & \\
\hline
Miembro de las Fuerzas Armadas y de Orden & 25 &  & 25 &  & 18 & \\
\hline
Patrón/a o empleador/a & 85 &  & 105 &  & 86 & \\
\hline
Trabaja solo, no tiene empleados & 321 &  & 409 &  & 345 & \\
\hline
Familiar no remunerado & 4 &  & 6 &  & 1 & \\
\hline
Servicio doméstico & 75 &  & 118 &  & 77 & \\
\hline
 & 1140 & 2473 & 1457 & 3417 & 1102 & 2730\\
\hline
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  m08. Su trabajo o negocio principal es de tipo:
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-8}Frecuencias de cada categoría de Temporalidad del trabajo por ola}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
temp\_trabajo & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Permanente & 1465 &  & 1766 &  & 1203 & \\
\hline
De temporada o estacional & 141 &  & 228 &  & 121 & \\
\hline
Ocasional o eventual & 125 &  & 180 &  & 195 & \\
\hline
A prueba & 9 &  & 18 &  & 10 & \\
\hline
Por plazo o tiempo determinado & 58 &  & 114 &  & 111 & \\
\hline
 & 1129 & 2473 & 1442 & 3417 & 1100 & 2730\\
\hline
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  m10. En su trabajo principal, ¿tiene contrato de trabajo escrito?
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-9}Frecuencias de cada categoría de Tipo de contrato por ola}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
contrato & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Sí, lo firmé & 1167 &  & 1445 &  & 999 & \\
\hline
Sí, pero no lo he firmado & 18 &  & 25 &  & 18 & \\
\hline
No tengo & 610 &  & 833 &  & 624 & \\
\hline
 & 1132 & 2473 & 1445 & 3417 & 1099 & 2730\\
\hline
\end{tabular}
\end{table}

\hypertarget{valoraciuxf3n-movimiento-de-demandas-laborales}{%
\subsection{Valoración Movimiento de Demandas Laborales}\label{valoraciuxf3n-movimiento-de-demandas-laborales}}

Considerando la pregunta de ELSOC:

\begin{itemize}
\tightlist
\item
  c20. Pensando en la lista de movimientos sociales que a continuación le mostraré, por favor indique ¿cuál es el que usted más valora?
\end{itemize}

Si consideramos \textbf{solamente} a las personas que responden que el movimiento que más valoran es el de ``Movimiento social de apoyo a demandas laborales'' tenemos:

\begin{table}

\caption{\label{tab:unnamed-chunk-10}Frecuencia de respuestas 'Movimiento social de apoyo a demandas laborales'}
\centering
\begin{tabular}[t]{r|r|r|r}
\hline
ola & n\_mov\_laboral & n\_ola & prop\\
\hline
1 & 381 & 2927 & 0.1301674\\
\hline
2 & 271 & 2473 & 0.1095835\\
\hline
3 & 228 & 3748 & 0.0608324\\
\hline
4 & 311 & 3417 & 0.0910155\\
\hline
5 & 459 & 2740 & 0.1675182\\
\hline
6 & 254 & 2730 & 0.0930403\\
\hline
\end{tabular}
\end{table}

El porcentaje más bajo de respuestas positivas se dio el año 2018 con un 6.08\% y el más alto el año 2021 con un 16.75\%. En promedio corresponde al 10.87\% de la muestra.

Esta variable tiene una serie de ítems asociados al nivel de acuerdo con afirmaciones respecto al movimiento social que más se valora.

\begin{itemize}
\item
  c21. Pensando en {[}movimiento social que más valora{]}, ¿cuán de acuerdo o en desacuerdo está usted con las siguientes afirmaciones?
\item
  c21\_01. Siento un compromiso con este movimiento
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-11}Frecuencias de 'Grado de acuerdo: Compromiso con el movimiento' por ola}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
compromiso\_mov & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Totalmente en desacuerdo & 4 & 1 & 3 &  &  & 4\\
\hline
En desacuerdo & 24 & 20 & 20 & 20 &  & 22\\
\hline
Ni en desacuerdo ni de acuerdo & 41 & 33 & 30 & 31 &  & 38\\
\hline
De acuerdo & 278 & 185 & 141 & 230 &  & 171\\
\hline
Totalmente de acuerdo & 30 & 32 & 32 & 30 &  & 18\\
\hline
 & 4 &  & 2 &  & 459 & 1\\
\hline
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  c21\_02. Me identifico con este movimiento
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-12}Frecuencias de 'Grado de acuerdo: Identificación con el movimiento' por ola}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
identificacion\_mov & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Totalmente en desacuerdo & 7 & 1 & 4 & 2 &  & 4\\
\hline
En desacuerdo & 18 & 16 & 14 & 12 &  & 24\\
\hline
Ni en desacuerdo ni de acuerdo & 35 & 36 & 20 & 31 &  & 35\\
\hline
De acuerdo & 298 & 188 & 161 & 239 &  & 176\\
\hline
Totalmente de acuerdo & 21 & 30 & 28 & 27 &  & 15\\
\hline
 & 2 &  & 1 &  & 459 & \\
\hline
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  c21\_05. Las acciones y protestas de este movimiento pueden generar un cambio social
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-13}Frecuencias de 'Grado de acuerdo: Acciones movimiento pueden generar cambio' por ola}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
acciones\_mov & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Totalmente en desacuerdo & 4 & 2 & 1 & 1 &  & 1\\
\hline
En desacuerdo & 18 & 18 & 10 & 15 &  & 20\\
\hline
Ni en desacuerdo ni de acuerdo & 46 & 42 & 27 & 22 &  & 31\\
\hline
De acuerdo & 276 & 179 & 153 & 214 &  & 172\\
\hline
Totalmente de acuerdo & 35 & 30 & 36 & 55 &  & 28\\
\hline
 & 2 &  & 1 & 4 & 459 & 2\\
\hline
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  c21\_09. Las autoridades y el movimiento tienen posiciones opuestas
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-14}Frecuencias de 'Grado de acuerdo: Posición opuesta entre el movimiento y las autoridades' por ola}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
opuesta\_mov & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Totalmente en desacuerdo & 6 & 3 & 2 & 1 &  & 2\\
\hline
En desacuerdo & 27 & 21 & 14 & 20 &  & 35\\
\hline
Ni en desacuerdo ni de acuerdo & 52 & 39 & 29 & 34 &  & 61\\
\hline
De acuerdo & 250 & 169 & 145 & 211 &  & 144\\
\hline
Totalmente de acuerdo & 37 & 33 & 30 & 37 &  & 6\\
\hline
 & 9 & 6 & 8 & 8 & 459 & 6\\
\hline
\end{tabular}
\end{table}

\begin{itemize}
\tightlist
\item
  c22. Ahora, pensando en los últimos 12 meses, cuán frecuntemente ha participado usted en {[}movimiento social que más valora{]}
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-15}Frecuencias de 'Frecuencia: Participación en el movimiento' por ola}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
participacion\_mov & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Nunca & 251 & 169 & 148 & 180 & 305 & 164\\
\hline
Casi nunca & 44 & 30 & 22 & 42 & 65 & 38\\
\hline
A veces & 57 & 54 & 38 & 71 & 69 & 37\\
\hline
Frecuentemente & 21 & 15 & 12 & 15 & 19 & 12\\
\hline
Muy Frecuentemente & 6 & 3 & 8 & 3 & 1 & 2\\
\hline
 & 2 &  &  &  &  & 1\\
\hline
\end{tabular}
\end{table}

\hypertarget{participaciuxf3n-en-sindicatos}{%
\subsection{Participación en sindicatos}\label{participaciuxf3n-en-sindicatos}}

\begin{itemize}
\tightlist
\item
  c12\_04. Membresía sindicatos
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-16}Frecuencias de cada categoría de Membresía Sindicatos por ola considerando toda la muestra}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
mem\_sindicato & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
No es miembro & 2613 &  & 3373 &  &  & 2329\\
\hline
Miembro inactivo & 89 &  & 108 &  &  & 48\\
\hline
Miembro activo & 214 &  & 258 &  &  & 193\\
\hline
 & 11 & 2473 & 9 & 3417 & 2740 & 160\\
\hline
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:unnamed-chunk-17}Frecuencias de Membresía Sindicato por ola, para quienes valoran movimientos laborales}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
mem\_sindicato & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
No es miembro & 314 &  & 173 &  &  & 203\\
\hline
Miembro inactivo & 12 &  & 16 &  &  & 7\\
\hline
Miembro activo & 55 &  & 39 &  &  & 25\\
\hline
 &  & 271 &  & 311 & 459 & 19\\
\hline
\end{tabular}
\end{table}

\hypertarget{participaciuxf3n-en-huelgas}{%
\subsection{Participación en huelgas}\label{participaciuxf3n-en-huelgas}}

\begin{itemize}
\tightlist
\item
  c08\_03. Durante los últimos 12 meses, con cuánta frecuencia usted ha participado en una huelga
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-18}Frecuencias de cada categoría de Participación en huelga por ola considerando toda la muestra}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
part\_huelga & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Nunca & 2547 & 2276 & 3407 & 3069 &  & 2594\\
\hline
Casi nunca & 122 & 78 & 152 & 135 &  & 74\\
\hline
A veces & 188 & 87 & 146 & 134 &  & 49\\
\hline
Frecuentemente & 49 & 25 & 29 & 54 &  & 11\\
\hline
Muy Frecuentemente & 15 & 7 & 11 & 22 &  & 2\\
\hline
 & 6 &  & 3 & 3 & 2740 & \\
\hline
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:unnamed-chunk-19}Frecuencias de Participación en huelga por ola, para quienes valoran movimientos laborales}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
part\_huelga & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Nunca & 319 & 236 & 196 & 269 &  & 238\\
\hline
Casi nunca & 17 & 12 & 12 & 13 &  & 10\\
\hline
A veces & 33 & 16 & 14 & 24 &  & 4\\
\hline
Frecuentemente & 7 & 6 & 4 & 4 &  & 2\\
\hline
Muy Frecuentemente & 5 & 1 & 2 & 1 &  & \\
\hline
 &  &  &  &  & 459 & \\
\hline
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:unnamed-chunk-20}Frecuencias de Participación en huelga por ola, para quienes son miembros de sindicatos (activos o inactivos)}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
part\_huelga & Ola\_1 & Ola\_3 & Ola\_6\\
\hline
Nunca & 205 & 259 & 198\\
\hline
Casi nunca & 25 & 46 & 23\\
\hline
A veces & 57 & 47 & 11\\
\hline
Frecuentemente & 11 & 8 & 8\\
\hline
Muy Frecuentemente & 5 & 6 & 1\\
\hline
\end{tabular}
\end{table}

\hypertarget{interuxe9s-en-poluxedtica}{%
\subsection{Interés en política}\label{interuxe9s-en-poluxedtica}}

\begin{itemize}
\tightlist
\item
  c13. ¿Qué tan interesado está usted en la política?
\end{itemize}

\begin{table}

\caption{\label{tab:unnamed-chunk-21}Frecuencias de cada categoría de Interés en la política por ola considerando toda la muestra}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
int\_politica & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Nada interesado & 1782 & 1269 & 2046 & 1602 & 1108 & 1381\\
\hline
Poco interesado & 509 & 507 & 753 & 674 & 713 & 520\\
\hline
Algo interesado & 365 & 379 & 563 & 601 & 532 & 472\\
\hline
Bastante interesado & 178 & 200 & 264 & 358 & 255 & 258\\
\hline
Muy interesado & 80 & 109 & 110 & 179 & 123 & 99\\
\hline
 & 13 & 9 & 12 & 3 & 9 & \\
\hline
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:unnamed-chunk-22}Frecuencias de Interés en la política por ola, para quienes valoran movimientos laborales}
\centering
\begin{tabular}[t]{l|r|r|r|r|r|r}
\hline
int\_politica & Ola\_1 & Ola\_2 & Ola\_3 & Ola\_4 & Ola\_5 & Ola\_6\\
\hline
Nada interesado & 220 & 123 & 121 & 156 & 197 & 108\\
\hline
Poco interesado & 62 & 63 & 44 & 70 & 129 & 59\\
\hline
Algo interesado & 66 & 52 & 38 & 53 & 83 & 52\\
\hline
Bastante interesado & 21 & 20 & 16 & 27 & 34 & 26\\
\hline
Muy interesado & 12 & 12 & 9 & 5 & 16 & 9\\
\hline
 &  & 1 &  &  &  & \\
\hline
\end{tabular}
\end{table}

\begin{table}

\caption{\label{tab:unnamed-chunk-23}Frecuencias de Interés en la política por ola, para quienes son miembros de sindicatos (activos o inactivos)}
\centering
\begin{tabular}[t]{l|r|r|r}
\hline
int\_politica & Ola\_1 & Ola\_3 & Ola\_6\\
\hline
Nada interesado & 158 & 173 & 78\\
\hline
Poco interesado & 49 & 79 & 55\\
\hline
Algo interesado & 55 & 62 & 51\\
\hline
Bastante interesado & 27 & 30 & 40\\
\hline
Muy interesado & 14 & 20 & 17\\
\hline
 &  & 2 & \\
\hline
\end{tabular}
\end{table}

\end{document}
