<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 1 Preparación y exploración datos | Efectos políticos de las huelgas</title>
  <meta name="description" content="Capítulo 1 Preparación y exploración datos | Efectos políticos de las huelgas" />
  <meta name="generator" content="bookdown 0.38 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 1 Preparación y exploración datos | Efectos políticos de las huelgas" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Capítulo 1 Preparación y exploración datos | Efectos políticos de las huelgas" />
  <meta name="github-repo" content="DaniOlivaresCollio/efectos-huelgas" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 1 Preparación y exploración datos | Efectos políticos de las huelgas" />
  
  <meta name="twitter:description" content="Capítulo 1 Preparación y exploración datos | Efectos políticos de las huelgas" />
  

<meta name="author" content="Equipo Fondecyt" />



  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="index.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>



<style type="text/css">
  
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
</style>

<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Efectos políticos de la huelgas </a></li>

<li class="divider"></li>
<li class="chapter" data-level="" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i>Presentación</a></li>
<li class="chapter" data-level="1" data-path="preparación-y-exploración-datos.html"><a href="preparación-y-exploración-datos.html"><i class="fa fa-check"></i><b>1</b> Preparación y exploración datos</a>
<ul>
<li class="chapter" data-level="1.1" data-path="preparación-y-exploración-datos.html"><a href="preparación-y-exploración-datos.html#exploración-variables-de-interés"><i class="fa fa-check"></i><b>1.1</b> Exploración variables de interés</a>
<ul>
<li class="chapter" data-level="1.1.1" data-path="preparación-y-exploración-datos.html"><a href="preparación-y-exploración-datos.html#caracterización-empleo"><i class="fa fa-check"></i><b>1.1.1</b> Caracterización empleo</a></li>
<li class="chapter" data-level="1.1.2" data-path="preparación-y-exploración-datos.html"><a href="preparación-y-exploración-datos.html#valoración-movimiento-de-demandas-laborales"><i class="fa fa-check"></i><b>1.1.2</b> Valoración Movimiento de Demandas Laborales</a></li>
<li class="chapter" data-level="1.1.3" data-path="preparación-y-exploración-datos.html"><a href="preparación-y-exploración-datos.html#participación-en-sindicatos"><i class="fa fa-check"></i><b>1.1.3</b> Participación en sindicatos</a></li>
<li class="chapter" data-level="1.1.4" data-path="preparación-y-exploración-datos.html"><a href="preparación-y-exploración-datos.html#participación-en-huelgas"><i class="fa fa-check"></i><b>1.1.4</b> Participación en huelgas</a></li>
<li class="chapter" data-level="1.1.5" data-path="preparación-y-exploración-datos.html"><a href="preparación-y-exploración-datos.html#interés-en-política"><i class="fa fa-check"></i><b>1.1.5</b> Interés en política</a></li>
</ul></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/DaniOlivaresCollio/efectos-huelgas" target="blank"> Ver fuente <i class="fa fa-github"></i></a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Efectos políticos de las huelgas</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="preparación-y-exploración-datos" class="section level1 hasAnchor" number="1">
<h1><span class="header-section-number">Capítulo 1</span> Preparación y exploración datos<a href="preparación-y-exploración-datos.html#preparación-y-exploración-datos" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<div style="text-align: justify">








<div id="exploración-variables-de-interés" class="section level2 hasAnchor" number="1.1">
<h2><span class="header-section-number">1.1</span> Exploración variables de interés<a href="preparación-y-exploración-datos.html#exploración-variables-de-interés" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<div id="caracterización-empleo" class="section level3 hasAnchor" number="1.1.1">
<h3><span class="header-section-number">1.1.1</span> Caracterización empleo<a href="preparación-y-exploración-datos.html#caracterización-empleo" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Primero, una revisión exploratoria de las variables de interés, considerando toda la base de datos, sin ponderar.</p>
<ul>
<li>m02. ¿Cuál de estas situaciones describe mejor su actividad principal durante el último mes?</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-1">Tabla 1.1: </span>Frecuencias de cada categoría de Actividad por ola</caption>
<colgroup>
<col width="58%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
<col width="6%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">actividad</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Trabaja de manera remunerada con jornada completa</td>
<td align="right">1391</td>
<td align="right">1116</td>
<td align="right">1688</td>
<td align="right">1501</td>
<td align="right">1095</td>
<td align="right">1137</td>
</tr>
<tr class="even">
<td align="left">Trabaja de manera remunerada a tiempo parcial</td>
<td align="right">351</td>
<td align="right">362</td>
<td align="right">537</td>
<td align="right">560</td>
<td align="right">484</td>
<td align="right">456</td>
</tr>
<tr class="odd">
<td align="left">Estudia y trabaja</td>
<td align="right">60</td>
<td align="right">71</td>
<td align="right">90</td>
<td align="right">68</td>
<td align="right">62</td>
<td align="right">49</td>
</tr>
<tr class="even">
<td align="left">Solo estudia</td>
<td align="right">101</td>
<td align="right">75</td>
<td align="right">116</td>
<td align="right">77</td>
<td align="right">51</td>
<td align="right">36</td>
</tr>
<tr class="odd">
<td align="left">Jubilado o pensionado</td>
<td align="right">371</td>
<td align="right">345</td>
<td align="right">479</td>
<td align="right">499</td>
<td align="right">433</td>
<td align="right">545</td>
</tr>
<tr class="even">
<td align="left">Desempleado, buscando trabajo</td>
<td align="right">166</td>
<td align="right">73</td>
<td align="right">198</td>
<td align="right">154</td>
<td align="right">172</td>
<td align="right">119</td>
</tr>
<tr class="odd">
<td align="left">Realiza tareas no remuneradas</td>
<td align="right">367</td>
<td align="right">332</td>
<td align="right">443</td>
<td align="right">449</td>
<td align="right">366</td>
<td align="right">294</td>
</tr>
<tr class="even">
<td align="left">Esta enfermo o tiene una discapacidad</td>
<td align="right">24</td>
<td align="right">17</td>
<td align="right">29</td>
<td align="right">32</td>
<td align="right">44</td>
<td align="right">28</td>
</tr>
<tr class="odd">
<td align="left">No estudia, no trabaja y no busca trabajo</td>
<td align="right">90</td>
<td align="right">77</td>
<td align="right">152</td>
<td align="right">67</td>
<td align="right">33</td>
<td align="right">59</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">6</td>
<td align="right">5</td>
<td align="right">16</td>
<td align="right">10</td>
<td align="right"></td>
<td align="right">7</td>
</tr>
</tbody>
</table>
<ul>
<li><p>m03. ¿Cuál es su ocupación u oficio actual? Describa sus principales tareas y funciones en el puesto de trabajo actual</p></li>
<li><p>ciuo88_m03: CIUO (1988) del entrevistado</p></li>
<li><p>ciuo08_m03: CIUO (2008) del entrevistado</p></li>
</ul>
<pre><code>## 
## 1229 1232 1239 1252 1312 1313 1314 1315 1316 1317 1318 1319 2114 2122 2131 2132 
##    1    1    1    1    3    2   52    8    2    7    1    3    2    1    5    1 
## 2141 2142 2143 2146 2147 2149 2211 2213 2221 2222 2223 2229 2230 2310 2320 2331 
##    5    4    3    1    2   19    2    2    3    2    1    2    8   10   10   32 
## 2332 2340 2359 2411 2412 2419 2421 2429 2432 2441 2442 2445 2446 2451 2452 2455 
##    7    3    3   12    1    6    5    2    5    1    1   10    8    4    1    1 
## 2460 3112 3114 3118 3121 3131 3132 3152 3212 3213 3221 3222 3223 3225 3226 3229 
##    1    7    2    1    6    2    1    9    4    2    5    2    4    3    3    2 
## 3231 3310 3320 3330 3340 3411 3412 3413 3415 3416 3417 3419 3422 3423 3432 3433 
##   17    1   10    2    4   10    4    5   13    2    1    2    2    8    1   14 
## 3441 3449 3452 3471 3472 3473 3474 3475 4113 4115 4121 4122 4131 4132 4133 4142 
##    1    1    2    4    2    5    1    4    2   49    4    5   27    6    4    2 
## 4190 4211 4215 4222 4223 5112 5121 5122 5123 5131 5132 5133 5141 5142 5162 5163 
##   56   22    2   12    4    1    3   56   20   39    6   10   21    1   12    2 
## 5164 5169 5220 5230 6111 6112 6113 6124 6141 6152 7111 7112 7122 7123 7124 7129 
##    6    4  141   36    5   11   17    1    6    1    5    1   27    5   41   11 
## 7134 7135 7136 7137 7141 7142 7212 7213 7221 7224 7231 7233 7241 7242 7243 7244 
##    2    1   10   18   14    8   23   10    1    1   27   15    3    4    1    2 
## 7245 7311 7313 7322 7343 7344 7345 7411 7412 7413 7415 7421 7422 7432 7433 7436 
##    1    3    1    1    1    1    1   12   27    1    3    2   16    3   16   16 
## 7437 7442 8112 8121 8124 8141 8143 8159 8163 8211 8221 8232 8240 8251 8264 8272 
##    1    3    1    1    1    4    1    1    2    4    2    4    1    3    1    1 
## 8275 8276 8311 8322 8323 8324 8331 8332 8333 8334 8340 9111 9112 9131 9132 9133 
##    1    1    2   35   23   26    9   10    1    5    3    3   14   80   71    2 
## 9141 9142 9151 9152 9153 9161 9162 9211 9312 9313 9322 9333 9955 9988 9999 
##    8    1    4   47    3    1    2   15    1   14    3    9    1    1    8</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre><code>## 
##  12  13  21  22  23  24  31  32  33  34  41  42  51  52  61  71  72  73  74  81 
##   4  78  43  20  65  58  28  42  17  82 155  40 181 177  41 143  88   8 100  11 
##  82  83  91  92  93  99 
##  18 114 236  15  27  10</code></pre>
<pre><code>## 
##  110  210  310 1112 1113 1114 1120 1211 1212 1219 1221 1311 1321 1322 1323 1324 
##    5    8    6    1    1    2    5    1    6    1    2    2    5    1    2    4 
## 1330 1342 1345 1346 1349 1411 1412 1420 1431 1439 2113 2114 2131 2132 2133 2139 
##    1    2    2    3    3    3   15   23    1    8    3    1    5    3    3    1 
## 2141 2142 2143 2144 2146 2149 2151 2152 2153 2161 2163 2164 2165 2166 2211 2212 
##    4    8    1    5    9   24    3    2    2   13    2    1    1    3    1   10 
## 2213 2221 2222 2230 2240 2243 2250 2261 2262 2263 2264 2265 2266 2269 2300 2310 
##    1   14    1    1    4    1    3    7    1    4    4    5    5    1    1   20 
## 2320 2330 2341 2342 2351 2352 2353 2356 2359 2411 2412 2413 2421 2422 2423 2431 
##    5   39   63   32    7   19    1    2   22   31    2    6    6    7    6    8 
## 2433 2434 2511 2512 2513 2519 2521 2523 2529 2611 2619 2622 2630 2631 2632 2634 
##    5    5    1    7    3    1    1    2    7   15    2    4    1    2    5   20 
## 2635 2636 2642 2652 2654 2655 2656 2659 3111 3112 3114 3116 3117 3118 3122 3123 
##   13    1    8    4    1    2    1    3    2    7    4    1    1    2    5   20 
## 3132 3133 3134 3139 3141 3142 3143 3144 3152 3154 3155 3211 3212 3213 3214 3221 
##    6    1    1    3    1    3    1    1    1    2    1    8    1    5    1   38 
## 3251 3253 3256 3257 3259 3311 3312 3313 3314 3315 3321 3322 3323 3324 3331 3332 
##   12    1    3    8    7    4    2    8    5    2   10    6    3    1    3    5 
## 3333 3334 3339 3341 3342 3343 3344 3352 3353 3354 3359 3411 3412 3422 3423 3431 
##    7   14    2    1    2   24    5    5    3    2    8    6    4    8    1    5 
## 3432 3434 3435 3512 3513 3522 3612 4110 4120 4121 4131 4132 4190 4211 4212 4214 
##    4    3    2    2    9    2    1   38   41    1    2    2    1   17    1    7 
## 4221 4222 4223 4224 4225 4226 4227 4229 4310 4311 4312 4313 4321 4322 4323 4411 
##    1    1   12    3    2   16    3    4    1   36    6    4   47    4   14    2 
## 4412 4415 4416 4419 4791 5112 5120 5131 5132 5141 5142 5151 5152 5153 5161 5163 
##    2    1    5   39    1    3   91   35    4   38   13    3    4   24    1    1 
## 5164 5211 5212 5221 5222 5223 5230 5242 5243 5244 5245 5246 5249 5311 5312 5321 
##    1   63   26  139   19  135   47   11    7    9    5    5   15   29   63   11 
## 5322 5329 5411 5412 5413 5414 5419 6110 6111 6112 6113 6122 6129 6151 6152 6210 
##   33    5    2   12    4   88    5    1    6    5   24    2    1    1    1    5 
## 6221 6222 6223 6310 6340 7111 7112 7113 7114 7115 7119 7121 7122 7123 7124 7126 
##    3    2    1    2    1   28   39    3    7   61    7    1    3    4    1   25 
## 7127 7130 7131 7132 7211 7212 7213 7214 7215 7221 7223 7224 7231 7232 7233 7311 
##    3    1   12   10    1   40   14    9    1    1    2    1   44    2   18    1 
## 7313 7316 7317 7318 7319 7322 7323 7411 7412 7413 7421 7422 7511 7512 7513 7514 
##    1    1    3    6    8   10    1   44    5    6    3    7   17   66    4    6 
## 7515 7521 7522 7531 7533 7534 7536 7542 7543 7544 8111 8112 8113 8114 8121 8122 
##    1    5   24   24   41    6    1    1    2    5    8    5    4    2    2    1 
## 8131 8141 8142 8143 8152 8153 8156 8157 8160 8171 8172 8182 8183 8189 8219 8312 
##    1    3    7    2    1    3    1    3   23    2   11    3    6    1    2    1 
## 8321 8322 8331 8332 8341 8342 8343 8344 8350 9111 9112 9121 9129 9211 9212 9213 
##    1   96   28   59    8   23   13    2    5  211  143    2    2   48    4    1 
## 9214 9215 9216 9311 9312 9313 9321 9329 9333 9334 9411 9412 9510 9520 9529 9611 
##   14    9    3    1    3   41   11    6   17   40    6   23    1   31    1    2 
## 9612 9613 9621 9622 9623 9629 9999 
##    2    5    9    1    2    2   54</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre><code>## 
##  11  12  13  14  21  22  23  24  25  26  31  32  33  34  35  36  41  42  43  44 
##  14  10  25  50 102  63 211  76  22  82  69  84 122  33  13   1  85  67 112  49 
##  47  51  52  53  54  61  62  63  71  72  73  74  75  81  82  83  91  92  93  94 
##   1 218 481 141 111  41  11   3 205 133  31  65 203  89   2 236 358  79 119  29 
##  95  96  99 
##  33  23  54</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre><code>## 
##   1   2   3   4   5   6   7   8   9 
##  82 186 169 195 358  41 339 143 288</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre><code>## 
##   1   2   3   4   5   6   7   8   9 
##  99 556 322 314 951  55 637 327 695</code></pre>
<ul>
<li><p>m04. ¿A qué rubro o giro de actividad se dedica principalmente la empresa, institución o negocio para la cual usted trabaja?</p></li>
<li><p>ciiu3_m04: CIIU (III version) del entrevistado</p></li>
<li><p>ciiu4_m04: CIIU (IV version) del entrevistado</p></li>
</ul>
<pre><code>## 
##  111  112  113  121  130  140  200  500 1110 1320 1410 1422 1511 1512 1514 1520 
##    2    4   26    2   12    8   20    7    1   26    1    1    7    1    1    4 
## 1531 1533 1541 1542 1543 1549 1552 1554 1711 1723 1730 1810 1912 1920 2010 2021 
##    6    2   28    1    3    1    3    5    1    2    2   31    2    1    7    5 
## 2101 2212 2221 2411 2423 2424 2429 2520 2610 2695 2710 2731 2811 2891 2893 2899 
##    6    1    7    1    3    1    1    2    1    1    6    1    6    3    1    4 
## 2912 2914 2919 2924 2929 3230 3511 3610 3691 3693 3720 4010 4100 4510 4520 4530 
##    1    1    3    2    1    1    1   16    1    1    1    1    3    2  135   38 
## 4540 4550 5010 5020 5030 5050 5121 5122 5139 5143 5149 5150 5190 5211 5219 5220 
##    9    1   14   33    3    4    2    5    2    1    1    2    3   69    1   53 
## 5231 5232 5233 5234 5239 5240 5252 5259 5260 5510 5520 6021 6022 6023 6110 6302 
##    9   21    3    7   26    2   47   10    1    5   69   28   16   36    6    5 
## 6303 6304 6411 6412 6420 6511 6519 6601 6602 6603 6711 6719 7010 7020 7111 7121 
##    4    1    2    2   19   10    4    2    3    6    1    1   11    7    1    1 
## 7123 7129 7210 7220 7240 7290 7310 7411 7412 7413 7414 7421 7422 7430 7491 7492 
##    1    2    1    5    1    1    2    8   11    1    5    8    2    3    8   32 
## 7493 7499 7511 7512 7513 7522 7523 8010 8021 8030 8090 8511 8512 8519 8520 8531 
##   25    6    9   19    2   13   19   89   37   27    8   23   44    6    2    7 
## 8532 9000 9191 9192 9199 9211 9213 9214 9219 9231 9233 9241 9249 9302 9309 9500 
##    1    3    4    1    1    1    2    5    5    1    5    4    6   17    7  150 
## 9999 
##   25</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre><code>## 
##  11  12  13  14  15  17  18  19  20  21  22  24  25  26  27  28  29  32  35  36 
##  33   2  38  10  62   5  31   3  32   6   8   6   2   2   7  14   8   1   1  18 
##  37  40  41  45  50  51  52  55  60  61  63  64  65  66  67  70  71  72  73  74 
##   1   1   3 185  61  16 249  74  80   6  10  23  14  11   2  18   5   8   2 109 
##  75  80  85  90  91  92  93  95  99 
##  62 161  83   3   6  29  24 150  25</code></pre>
<pre><code>## 
##   111   113   119   121   122   123   124   125   130   141   146   150   151 
##    15     8     2     9     5     1    27     2     3     1     4     7     1 
##   161   210   220   311   321   400   510   710   729   810   899  1000  1010 
##     8    28     6    19     3    41     1     1     3    11     1     4     9 
##  1020  1030  1040  1050  1061  1062  1071  1073  1074  1075  1079  1080  1101 
##     8    10     1    15     3     2    77     5     4     2     9     3     1 
##  1104  1120  1192  1230  1311  1312  1391  1392  1399  1410  1430  1512  1520 
##     4     1     1     2     1     2     2     7     3    52     2     2     3 
##  1610  1621  1622  1623  1629  1701  1702  1709  1710  1811  1920  2011  2013 
##    21     4     1     1     1    10     2     4     1    15     2     4     3 
##  2021  2022  2023  2100  2211  2220  2391  2395  2400  2410  2411  2431  2432 
##     1     2     3     8     3     8     1     4     2     7     2     1     1 
##  2511  2512  2591  2592  2599  2611  2640  2670  2815  2819  2821  2824  2829 
##    19     1     1     1     3     3     1     1     2     1     1     4     2 
##  3011  3020  3100  3111  3211  3212  3240  3290  3311  3312  3313  3314  3319 
##     1     1    26     1     1     1     1     2     1     8     2     3     1 
##  3320  3431  3510  3520  3530  3600  3811  3821  3830  4000  4100  4200  4210 
##     3     1    10     7     1    10     3     1     2     7   227     1    11 
##  4220  4290  4312  4320  4321  4322  4329  4330  4390  4510  4520  4530  4540 
##     3    16     4     1    29    21     1    32    12    15    55    11     1 
##  4610  4620  4630  4641  4649  4651  4653  4659  4661  4663  4669  4690  4700 
##     3     9    21     9     5     2     3     3     3     4     1     3     1 
##  4711  4719  4721  4722  4730  4740  4741  4751  4752  4753  4759  4761  4763 
##   145    59    85    10     8     1    10     6    18     3     4     6     1 
##  4764  4771  4772  4773  4774  4781  4782  4789  4791  4799  4911  4912  4921 
##     3    23    29    32     5    18    15    29    12    37     1     1    64 
##  4922  4923  5010  5011  5012  5021  5110  5120  5210  5221  5222  5223  5224 
##    50    64     1     1     7     1     4     1    24     4     8     1     1 
##  5229  5310  5320  5510  5610  5621  5629  5630  5813  5914  6010  6020  6100 
##     7     4     1    17   161     4    12     2     2     2     1     4     1 
##  6110  6120  6190  6201  6202  6209  6312  6411  6419  6430  6449  6492  6499 
##    18    12     1     5    12     3     1     8    16     1     1     1     2 
##  6511  6512  6619  6621  6622  6629  6630  6810  6820  6910  6920  7020  7100 
##     4     9     2     1     3     1     2    18     6    16    25    12     1 
##  7110  7120  7210  7310  7320  7410  7420  7500  7710  7730  7810  7830  7911 
##    19     4     6    13     5     4     2     6     2     7     4     8     1 
##  7912  8010  8020  8110  8121  8129  8130  8211  8220  8291  8299  8411  8412 
##     2    49     5     2    57    10    18     7     5     1     1   100    47 
##  8413  8421  8422  8423  8430  8500  8531  8532  8541  8549  8550  8610  8620 
##     3     1    28    23     1   287    44    12     5     6     4   147    43 
##  8690  8730  8790  8888  8890  9000  9103  9200  9311  9312  9319  9321  9329 
##    15     6    14     2     4    15     2     4     8     3     1     1     6 
##  9411  9412  9491  9492  9499  9511  9521  9524  9529  9601  9602  9603  9609 
##     3     2     4     1     5     6     1     4    13     7    52     5     7 
##  9700  9999 72820 
##   300    89     1</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre><code>## 
##  10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  28  30  31 
## 152  32  46  18  59  13  36  17  15   2  13  36  17   5  13  25   5  10   2  46 
##  32  33  34  35  36  38  40  41  42  43  45  46  47  49  50  51  52  53  55  56 
##   8  18   1  18  10   6  48 227  31 100  82  66 560 180  10   6  45   5  17 179 
##  58  59  60  61  62  63  64  65  66  68  69  70  71  72  73  74  75  77  78  79 
##   2   2   5  32  20   1  29  13   9  24  41  12  25  10  18   6   6   9  12   3 
##  80  81  82  84  85  86  87  88  89  90  91  92  93  94  95  96  97  99 
##  54  98  14 203 358 205  20   6   1  15   2   4  19  15  24  71 300  89</code></pre>
<pre><code>## [1] &quot;numeric&quot;</code></pre>
<pre><code>## 
##    1    2    3    4    5    6    7    8    9 
##  390  124  109 1294  266  174  101  959  539</code></pre>
<ul>
<li>m07. En su actual ocupación usted trabaja como:</li>
</ul>
<table style="width:100%;">
<caption><span id="tab:unnamed-chunk-4">Tabla 1.2: </span>Frecuencias de cada categoría de Relación de Empleo por ola</caption>
<colgroup>
<col width="53%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">rel_empleo</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Empleado u obrero en empresa privada</td>
<td align="right">1091</td>
<td align="right"></td>
<td align="right">1338</td>
<td align="right"></td>
<td align="right">883</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">Empleado u obrero del sector público</td>
<td align="right">186</td>
<td align="right"></td>
<td align="right">290</td>
<td align="right"></td>
<td align="right">228</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">Miembro de las Fuerzas Armadas y de Orden</td>
<td align="right">25</td>
<td align="right"></td>
<td align="right">25</td>
<td align="right"></td>
<td align="right">18</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">Patrón/a o empleador/a</td>
<td align="right">85</td>
<td align="right"></td>
<td align="right">105</td>
<td align="right"></td>
<td align="right">86</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">Trabaja solo, no tiene empleados</td>
<td align="right">321</td>
<td align="right"></td>
<td align="right">409</td>
<td align="right"></td>
<td align="right">345</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">Familiar no remunerado</td>
<td align="right">4</td>
<td align="right"></td>
<td align="right">6</td>
<td align="right"></td>
<td align="right">1</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">Servicio doméstico</td>
<td align="right">75</td>
<td align="right"></td>
<td align="right">118</td>
<td align="right"></td>
<td align="right">77</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">1140</td>
<td align="right">2473</td>
<td align="right">1457</td>
<td align="right">3417</td>
<td align="right">1102</td>
<td align="right">2730</td>
</tr>
</tbody>
</table>
<ul>
<li>m08. Su trabajo o negocio principal es de tipo:</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-5">Tabla 1.3: </span>Frecuencias de cada categoría de Temporalidad del trabajo por ola</caption>
<colgroup>
<col width="46%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">temp_trabajo</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Permanente</td>
<td align="right">1465</td>
<td align="right"></td>
<td align="right">1766</td>
<td align="right"></td>
<td align="right">1203</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">De temporada o estacional</td>
<td align="right">141</td>
<td align="right"></td>
<td align="right">228</td>
<td align="right"></td>
<td align="right">121</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">Ocasional o eventual</td>
<td align="right">125</td>
<td align="right"></td>
<td align="right">180</td>
<td align="right"></td>
<td align="right">195</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">A prueba</td>
<td align="right">9</td>
<td align="right"></td>
<td align="right">18</td>
<td align="right"></td>
<td align="right">10</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">Por plazo o tiempo determinado</td>
<td align="right">58</td>
<td align="right"></td>
<td align="right">114</td>
<td align="right"></td>
<td align="right">111</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">1129</td>
<td align="right">2473</td>
<td align="right">1442</td>
<td align="right">3417</td>
<td align="right">1100</td>
<td align="right">2730</td>
</tr>
</tbody>
</table>
<ul>
<li>m10. En su trabajo principal, ¿tiene contrato de trabajo escrito?</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-6">Tabla 1.4: </span>Frecuencias de cada categoría de Tipo de contrato por ola</caption>
<thead>
<tr class="header">
<th align="left">contrato</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Sí, lo firmé</td>
<td align="right">1167</td>
<td align="right"></td>
<td align="right">1445</td>
<td align="right"></td>
<td align="right">999</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left">Sí, pero no lo he firmado</td>
<td align="right">18</td>
<td align="right"></td>
<td align="right">25</td>
<td align="right"></td>
<td align="right">18</td>
<td align="right"></td>
</tr>
<tr class="odd">
<td align="left">No tengo</td>
<td align="right">610</td>
<td align="right"></td>
<td align="right">833</td>
<td align="right"></td>
<td align="right">624</td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">1132</td>
<td align="right">2473</td>
<td align="right">1445</td>
<td align="right">3417</td>
<td align="right">1099</td>
<td align="right">2730</td>
</tr>
</tbody>
</table>
</div>
<div id="valoración-movimiento-de-demandas-laborales" class="section level3 hasAnchor" number="1.1.2">
<h3><span class="header-section-number">1.1.2</span> Valoración Movimiento de Demandas Laborales<a href="preparación-y-exploración-datos.html#valoración-movimiento-de-demandas-laborales" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<p>Considerando la pregunta de ELSOC:</p>
<ul>
<li>c20. Pensando en la lista de movimientos sociales que a continuación le mostraré, por favor indique ¿cuál es el que usted más valora?</li>
</ul>
<p>Si consideramos <strong>solamente</strong> a las personas que responden que el movimiento que más valoran es el de “Movimiento social de apoyo a demandas laborales” tenemos:</p>
<table>
<caption><span id="tab:unnamed-chunk-7">Tabla 1.5: </span>Frecuencia de respuestas ‘Movimiento social de apoyo a demandas laborales’</caption>
<thead>
<tr class="header">
<th align="right">ola</th>
<th align="right">n_mov_laboral</th>
<th align="right">n_ola</th>
<th align="right">prop</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="right">1</td>
<td align="right">381</td>
<td align="right">2927</td>
<td align="right">0.1301674</td>
</tr>
<tr class="even">
<td align="right">2</td>
<td align="right">271</td>
<td align="right">2473</td>
<td align="right">0.1095835</td>
</tr>
<tr class="odd">
<td align="right">3</td>
<td align="right">228</td>
<td align="right">3748</td>
<td align="right">0.0608324</td>
</tr>
<tr class="even">
<td align="right">4</td>
<td align="right">311</td>
<td align="right">3417</td>
<td align="right">0.0910155</td>
</tr>
<tr class="odd">
<td align="right">5</td>
<td align="right">459</td>
<td align="right">2740</td>
<td align="right">0.1675182</td>
</tr>
<tr class="even">
<td align="right">6</td>
<td align="right">254</td>
<td align="right">2730</td>
<td align="right">0.0930403</td>
</tr>
</tbody>
</table>
<p>El porcentaje más bajo de respuestas positivas se dio el año 2018 con un 6.08% y el más alto el año 2021 con un 16.75%. En promedio corresponde al 10.87% de la muestra.</p>
<p>Esta variable tiene una serie de ítems asociados al nivel de acuerdo con afirmaciones respecto al movimiento social que más se valora.</p>
<ul>
<li><p>c21. Pensando en [movimiento social que más valora], ¿cuán de acuerdo o en desacuerdo está usted con las siguientes afirmaciones?</p></li>
<li><p>c21_01. Siento un compromiso con este movimiento</p></li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-8">Tabla 1.6: </span>Frecuencias de ‘Grado de acuerdo: Compromiso con el movimiento’ por ola</caption>
<colgroup>
<col width="46%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">compromiso_mov</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Totalmente en desacuerdo</td>
<td align="right">4</td>
<td align="right">1</td>
<td align="right">3</td>
<td align="right"></td>
<td align="right"></td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="left">En desacuerdo</td>
<td align="right">24</td>
<td align="right">20</td>
<td align="right">20</td>
<td align="right">20</td>
<td align="right"></td>
<td align="right">22</td>
</tr>
<tr class="odd">
<td align="left">Ni en desacuerdo ni de acuerdo</td>
<td align="right">41</td>
<td align="right">33</td>
<td align="right">30</td>
<td align="right">31</td>
<td align="right"></td>
<td align="right">38</td>
</tr>
<tr class="even">
<td align="left">De acuerdo</td>
<td align="right">278</td>
<td align="right">185</td>
<td align="right">141</td>
<td align="right">230</td>
<td align="right"></td>
<td align="right">171</td>
</tr>
<tr class="odd">
<td align="left">Totalmente de acuerdo</td>
<td align="right">30</td>
<td align="right">32</td>
<td align="right">32</td>
<td align="right">30</td>
<td align="right"></td>
<td align="right">18</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">4</td>
<td align="right"></td>
<td align="right">2</td>
<td align="right"></td>
<td align="right">459</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
<ul>
<li>c21_02. Me identifico con este movimiento</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-9">Tabla 1.7: </span>Frecuencias de ‘Grado de acuerdo: Identificación con el movimiento’ por ola</caption>
<colgroup>
<col width="46%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">identificacion_mov</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Totalmente en desacuerdo</td>
<td align="right">7</td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">2</td>
<td align="right"></td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="left">En desacuerdo</td>
<td align="right">18</td>
<td align="right">16</td>
<td align="right">14</td>
<td align="right">12</td>
<td align="right"></td>
<td align="right">24</td>
</tr>
<tr class="odd">
<td align="left">Ni en desacuerdo ni de acuerdo</td>
<td align="right">35</td>
<td align="right">36</td>
<td align="right">20</td>
<td align="right">31</td>
<td align="right"></td>
<td align="right">35</td>
</tr>
<tr class="even">
<td align="left">De acuerdo</td>
<td align="right">298</td>
<td align="right">188</td>
<td align="right">161</td>
<td align="right">239</td>
<td align="right"></td>
<td align="right">176</td>
</tr>
<tr class="odd">
<td align="left">Totalmente de acuerdo</td>
<td align="right">21</td>
<td align="right">30</td>
<td align="right">28</td>
<td align="right">27</td>
<td align="right"></td>
<td align="right">15</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">2</td>
<td align="right"></td>
<td align="right">1</td>
<td align="right"></td>
<td align="right">459</td>
<td align="right"></td>
</tr>
</tbody>
</table>
<ul>
<li>c21_05. Las acciones y protestas de este movimiento pueden generar un cambio social</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-10">Tabla 1.8: </span>Frecuencias de ‘Grado de acuerdo: Acciones movimiento pueden generar cambio’ por ola</caption>
<colgroup>
<col width="46%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">acciones_mov</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Totalmente en desacuerdo</td>
<td align="right">4</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right">1</td>
<td align="right"></td>
<td align="right">1</td>
</tr>
<tr class="even">
<td align="left">En desacuerdo</td>
<td align="right">18</td>
<td align="right">18</td>
<td align="right">10</td>
<td align="right">15</td>
<td align="right"></td>
<td align="right">20</td>
</tr>
<tr class="odd">
<td align="left">Ni en desacuerdo ni de acuerdo</td>
<td align="right">46</td>
<td align="right">42</td>
<td align="right">27</td>
<td align="right">22</td>
<td align="right"></td>
<td align="right">31</td>
</tr>
<tr class="even">
<td align="left">De acuerdo</td>
<td align="right">276</td>
<td align="right">179</td>
<td align="right">153</td>
<td align="right">214</td>
<td align="right"></td>
<td align="right">172</td>
</tr>
<tr class="odd">
<td align="left">Totalmente de acuerdo</td>
<td align="right">35</td>
<td align="right">30</td>
<td align="right">36</td>
<td align="right">55</td>
<td align="right"></td>
<td align="right">28</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">2</td>
<td align="right"></td>
<td align="right">1</td>
<td align="right">4</td>
<td align="right">459</td>
<td align="right">2</td>
</tr>
</tbody>
</table>
<ul>
<li>c21_09. Las autoridades y el movimiento tienen posiciones opuestas</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-11">Tabla 1.9: </span>Frecuencias de ‘Grado de acuerdo: Posición opuesta entre el movimiento y las autoridades’ por ola</caption>
<colgroup>
<col width="46%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th align="left">opuesta_mov</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Totalmente en desacuerdo</td>
<td align="right">6</td>
<td align="right">3</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right"></td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left">En desacuerdo</td>
<td align="right">27</td>
<td align="right">21</td>
<td align="right">14</td>
<td align="right">20</td>
<td align="right"></td>
<td align="right">35</td>
</tr>
<tr class="odd">
<td align="left">Ni en desacuerdo ni de acuerdo</td>
<td align="right">52</td>
<td align="right">39</td>
<td align="right">29</td>
<td align="right">34</td>
<td align="right"></td>
<td align="right">61</td>
</tr>
<tr class="even">
<td align="left">De acuerdo</td>
<td align="right">250</td>
<td align="right">169</td>
<td align="right">145</td>
<td align="right">211</td>
<td align="right"></td>
<td align="right">144</td>
</tr>
<tr class="odd">
<td align="left">Totalmente de acuerdo</td>
<td align="right">37</td>
<td align="right">33</td>
<td align="right">30</td>
<td align="right">37</td>
<td align="right"></td>
<td align="right">6</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">9</td>
<td align="right">6</td>
<td align="right">8</td>
<td align="right">8</td>
<td align="right">459</td>
<td align="right">6</td>
</tr>
</tbody>
</table>
<ul>
<li>c22. Ahora, pensando en los últimos 12 meses, cuán frecuntemente ha participado usted en [movimiento social que más valora]</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-12">Tabla 1.10: </span>Frecuencias de ‘Frecuencia: Participación en el movimiento’ por ola</caption>
<thead>
<tr class="header">
<th align="left">participacion_mov</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Nunca</td>
<td align="right">251</td>
<td align="right">169</td>
<td align="right">148</td>
<td align="right">180</td>
<td align="right">305</td>
<td align="right">164</td>
</tr>
<tr class="even">
<td align="left">Casi nunca</td>
<td align="right">44</td>
<td align="right">30</td>
<td align="right">22</td>
<td align="right">42</td>
<td align="right">65</td>
<td align="right">38</td>
</tr>
<tr class="odd">
<td align="left">A veces</td>
<td align="right">57</td>
<td align="right">54</td>
<td align="right">38</td>
<td align="right">71</td>
<td align="right">69</td>
<td align="right">37</td>
</tr>
<tr class="even">
<td align="left">Frecuentemente</td>
<td align="right">21</td>
<td align="right">15</td>
<td align="right">12</td>
<td align="right">15</td>
<td align="right">19</td>
<td align="right">12</td>
</tr>
<tr class="odd">
<td align="left">Muy Frecuentemente</td>
<td align="right">6</td>
<td align="right">3</td>
<td align="right">8</td>
<td align="right">3</td>
<td align="right">1</td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">2</td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right">1</td>
</tr>
</tbody>
</table>
</div>
<div id="participación-en-sindicatos" class="section level3 hasAnchor" number="1.1.3">
<h3><span class="header-section-number">1.1.3</span> Participación en sindicatos<a href="preparación-y-exploración-datos.html#participación-en-sindicatos" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>c12_04. Membresía sindicatos</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-13">Tabla 1.11: </span>Frecuencias de cada categoría de Membresía Sindicatos por ola considerando toda la muestra</caption>
<thead>
<tr class="header">
<th align="left">mem_sindicato</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">No es miembro</td>
<td align="right">2613</td>
<td align="right"></td>
<td align="right">3373</td>
<td align="right"></td>
<td align="right"></td>
<td align="right">2329</td>
</tr>
<tr class="even">
<td align="left">Miembro inactivo</td>
<td align="right">89</td>
<td align="right"></td>
<td align="right">108</td>
<td align="right"></td>
<td align="right"></td>
<td align="right">48</td>
</tr>
<tr class="odd">
<td align="left">Miembro activo</td>
<td align="right">214</td>
<td align="right"></td>
<td align="right">258</td>
<td align="right"></td>
<td align="right"></td>
<td align="right">193</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">11</td>
<td align="right">2473</td>
<td align="right">9</td>
<td align="right">3417</td>
<td align="right">2740</td>
<td align="right">160</td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:unnamed-chunk-14">Tabla 1.12: </span>Frecuencias de Membresía Sindicato por ola, para quienes valoran movimientos laborales</caption>
<thead>
<tr class="header">
<th align="left">mem_sindicato</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">No es miembro</td>
<td align="right">314</td>
<td align="right"></td>
<td align="right">173</td>
<td align="right"></td>
<td align="right"></td>
<td align="right">203</td>
</tr>
<tr class="even">
<td align="left">Miembro inactivo</td>
<td align="right">12</td>
<td align="right"></td>
<td align="right">16</td>
<td align="right"></td>
<td align="right"></td>
<td align="right">7</td>
</tr>
<tr class="odd">
<td align="left">Miembro activo</td>
<td align="right">55</td>
<td align="right"></td>
<td align="right">39</td>
<td align="right"></td>
<td align="right"></td>
<td align="right">25</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right"></td>
<td align="right">271</td>
<td align="right"></td>
<td align="right">311</td>
<td align="right">459</td>
<td align="right">19</td>
</tr>
</tbody>
</table>
</div>
<div id="participación-en-huelgas" class="section level3 hasAnchor" number="1.1.4">
<h3><span class="header-section-number">1.1.4</span> Participación en huelgas<a href="preparación-y-exploración-datos.html#participación-en-huelgas" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>c08_03. Durante los últimos 12 meses, con cuánta frecuencia usted ha participado en una huelga</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-15">Tabla 1.13: </span>Frecuencias de cada categoría de Participación en huelga por ola considerando toda la muestra</caption>
<thead>
<tr class="header">
<th align="left">part_huelga</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Nunca</td>
<td align="right">2547</td>
<td align="right">2276</td>
<td align="right">3407</td>
<td align="right">3069</td>
<td align="right"></td>
<td align="right">2594</td>
</tr>
<tr class="even">
<td align="left">Casi nunca</td>
<td align="right">122</td>
<td align="right">78</td>
<td align="right">152</td>
<td align="right">135</td>
<td align="right"></td>
<td align="right">74</td>
</tr>
<tr class="odd">
<td align="left">A veces</td>
<td align="right">188</td>
<td align="right">87</td>
<td align="right">146</td>
<td align="right">134</td>
<td align="right"></td>
<td align="right">49</td>
</tr>
<tr class="even">
<td align="left">Frecuentemente</td>
<td align="right">49</td>
<td align="right">25</td>
<td align="right">29</td>
<td align="right">54</td>
<td align="right"></td>
<td align="right">11</td>
</tr>
<tr class="odd">
<td align="left">Muy Frecuentemente</td>
<td align="right">15</td>
<td align="right">7</td>
<td align="right">11</td>
<td align="right">22</td>
<td align="right"></td>
<td align="right">2</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">6</td>
<td align="right"></td>
<td align="right">3</td>
<td align="right">3</td>
<td align="right">2740</td>
<td align="right"></td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:unnamed-chunk-16">Tabla 1.14: </span>Frecuencias de Participación en huelga por ola, para quienes valoran movimientos laborales</caption>
<thead>
<tr class="header">
<th align="left">part_huelga</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Nunca</td>
<td align="right">319</td>
<td align="right">236</td>
<td align="right">196</td>
<td align="right">269</td>
<td align="right"></td>
<td align="right">238</td>
</tr>
<tr class="even">
<td align="left">Casi nunca</td>
<td align="right">17</td>
<td align="right">12</td>
<td align="right">12</td>
<td align="right">13</td>
<td align="right"></td>
<td align="right">10</td>
</tr>
<tr class="odd">
<td align="left">A veces</td>
<td align="right">33</td>
<td align="right">16</td>
<td align="right">14</td>
<td align="right">24</td>
<td align="right"></td>
<td align="right">4</td>
</tr>
<tr class="even">
<td align="left">Frecuentemente</td>
<td align="right">7</td>
<td align="right">6</td>
<td align="right">4</td>
<td align="right">4</td>
<td align="right"></td>
<td align="right">2</td>
</tr>
<tr class="odd">
<td align="left">Muy Frecuentemente</td>
<td align="right">5</td>
<td align="right">1</td>
<td align="right">2</td>
<td align="right">1</td>
<td align="right"></td>
<td align="right"></td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right">459</td>
<td align="right"></td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:unnamed-chunk-17">Tabla 1.15: </span>Frecuencias de Participación en huelga por ola, para quienes son miembros de sindicatos (activos o inactivos)</caption>
<thead>
<tr class="header">
<th align="left">part_huelga</th>
<th align="right">Ola_1</th>
<th align="right">Ola_3</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Nunca</td>
<td align="right">205</td>
<td align="right">259</td>
<td align="right">198</td>
</tr>
<tr class="even">
<td align="left">Casi nunca</td>
<td align="right">25</td>
<td align="right">46</td>
<td align="right">23</td>
</tr>
<tr class="odd">
<td align="left">A veces</td>
<td align="right">57</td>
<td align="right">47</td>
<td align="right">11</td>
</tr>
<tr class="even">
<td align="left">Frecuentemente</td>
<td align="right">11</td>
<td align="right">8</td>
<td align="right">8</td>
</tr>
<tr class="odd">
<td align="left">Muy Frecuentemente</td>
<td align="right">5</td>
<td align="right">6</td>
<td align="right">1</td>
</tr>
</tbody>
</table>
</div>
<div id="interés-en-política" class="section level3 hasAnchor" number="1.1.5">
<h3><span class="header-section-number">1.1.5</span> Interés en política<a href="preparación-y-exploración-datos.html#interés-en-política" class="anchor-section" aria-label="Anchor link to header"></a></h3>
<ul>
<li>c13. ¿Qué tan interesado está usted en la política?</li>
</ul>
<table>
<caption><span id="tab:unnamed-chunk-18">Tabla 1.16: </span>Frecuencias de cada categoría de Interés en la política por ola considerando toda la muestra</caption>
<thead>
<tr class="header">
<th align="left">int_politica</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Nada interesado</td>
<td align="right">1782</td>
<td align="right">1269</td>
<td align="right">2046</td>
<td align="right">1602</td>
<td align="right">1108</td>
<td align="right">1381</td>
</tr>
<tr class="even">
<td align="left">Poco interesado</td>
<td align="right">509</td>
<td align="right">507</td>
<td align="right">753</td>
<td align="right">674</td>
<td align="right">713</td>
<td align="right">520</td>
</tr>
<tr class="odd">
<td align="left">Algo interesado</td>
<td align="right">365</td>
<td align="right">379</td>
<td align="right">563</td>
<td align="right">601</td>
<td align="right">532</td>
<td align="right">472</td>
</tr>
<tr class="even">
<td align="left">Bastante interesado</td>
<td align="right">178</td>
<td align="right">200</td>
<td align="right">264</td>
<td align="right">358</td>
<td align="right">255</td>
<td align="right">258</td>
</tr>
<tr class="odd">
<td align="left">Muy interesado</td>
<td align="right">80</td>
<td align="right">109</td>
<td align="right">110</td>
<td align="right">179</td>
<td align="right">123</td>
<td align="right">99</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right">13</td>
<td align="right">9</td>
<td align="right">12</td>
<td align="right">3</td>
<td align="right">9</td>
<td align="right"></td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:unnamed-chunk-19">Tabla 1.17: </span>Frecuencias de Interés en la política por ola, para quienes valoran movimientos laborales</caption>
<thead>
<tr class="header">
<th align="left">int_politica</th>
<th align="right">Ola_1</th>
<th align="right">Ola_2</th>
<th align="right">Ola_3</th>
<th align="right">Ola_4</th>
<th align="right">Ola_5</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Nada interesado</td>
<td align="right">220</td>
<td align="right">123</td>
<td align="right">121</td>
<td align="right">156</td>
<td align="right">197</td>
<td align="right">108</td>
</tr>
<tr class="even">
<td align="left">Poco interesado</td>
<td align="right">62</td>
<td align="right">63</td>
<td align="right">44</td>
<td align="right">70</td>
<td align="right">129</td>
<td align="right">59</td>
</tr>
<tr class="odd">
<td align="left">Algo interesado</td>
<td align="right">66</td>
<td align="right">52</td>
<td align="right">38</td>
<td align="right">53</td>
<td align="right">83</td>
<td align="right">52</td>
</tr>
<tr class="even">
<td align="left">Bastante interesado</td>
<td align="right">21</td>
<td align="right">20</td>
<td align="right">16</td>
<td align="right">27</td>
<td align="right">34</td>
<td align="right">26</td>
</tr>
<tr class="odd">
<td align="left">Muy interesado</td>
<td align="right">12</td>
<td align="right">12</td>
<td align="right">9</td>
<td align="right">5</td>
<td align="right">16</td>
<td align="right">9</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right"></td>
<td align="right">1</td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
<td align="right"></td>
</tr>
</tbody>
</table>
<table>
<caption><span id="tab:unnamed-chunk-20">Tabla 1.18: </span>Frecuencias de Interés en la política por ola, para quienes son miembros de sindicatos (activos o inactivos)</caption>
<thead>
<tr class="header">
<th align="left">int_politica</th>
<th align="right">Ola_1</th>
<th align="right">Ola_3</th>
<th align="right">Ola_6</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">Nada interesado</td>
<td align="right">158</td>
<td align="right">173</td>
<td align="right">78</td>
</tr>
<tr class="even">
<td align="left">Poco interesado</td>
<td align="right">49</td>
<td align="right">79</td>
<td align="right">55</td>
</tr>
<tr class="odd">
<td align="left">Algo interesado</td>
<td align="right">55</td>
<td align="right">62</td>
<td align="right">51</td>
</tr>
<tr class="even">
<td align="left">Bastante interesado</td>
<td align="right">27</td>
<td align="right">30</td>
<td align="right">40</td>
</tr>
<tr class="odd">
<td align="left">Muy interesado</td>
<td align="right">14</td>
<td align="right">20</td>
<td align="right">17</td>
</tr>
<tr class="even">
<td align="left"></td>
<td align="right"></td>
<td align="right">2</td>
<td align="right"></td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="index.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": true,
"facebook": false,
"twitter": false,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": null,
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": ["efectos-huelgas.pdf"],
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "subsection"
},
"info": false
});
});
</script>

</body>

</html>
